[package]
name = "mithya_engine"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glam = { version = "0.24", features = ["serde"] }
gl = "0.14.0"
image = "0.24"
sdl2 = { version = "0.37.0", features = ["bundled", "static-link"] }
egui = "0.32"
egui_sdl2_gl = "0.32"
thiserror = "2.0.16"

[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.5"
