[package]
name = "mithya_engine"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
glam = { version = "0.24", features = ["serde"] }
image = "0.24"
thiserror = "2.0.16"
winit = "0.30"
wgpu = "24"
egui = "0.31"
egui-wgpu = "0.31"
egui-winit = "0.31"
bytemuck = "1"
pollster = "0.3"
